#!/usr/bin/env bash


DOTFILES=${DOTFILES:-"$HOME/.dotfiles"}
STOW_FOLDERS=${STOW_FOLDERS:-"alacritty,awesome,bin,brightctl,dunst,git,htop,latex,notify-bar,profile-KoroSensei,termite,tmux,vconf,vim,volumectl,wallpapers,wd,zathura,zsh"}

pushd $DOTFILES > /dev/null

IFS=','; for folder in $STOW_FOLDERS; do
    stow -D "$folder"
    stow "$folder"
    echo "Installing $folder"
done

popd > /dev/null
