#!/usr/bin/env bash


[[ -z "${DOTFILES+x}" ]] && DOTFILES="$HOME/.dotfiles"

[[ -z "${STOW_FOLDERS+x}" ]] && STOW_FOLDERS="bin,dunst,htop,latex,profile-DrStone,termite,vconf,vim,zsh,zathura"

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
