#!/usr/bin/env bash


[[ -z "${DOTFILES+x}" ]] && DOTFILES="$HOME/.dotfiles"

[[ -z "${STOW_FOLDERS+x}" ]] && STOW_FOLDERS="bin,brightctl,dunst,htop,latex,notify-bar,profile,termite,vconf,vim,volumectl,zsh"

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
