if has("nvim")
    finish
endif
" XDG
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup 
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set nocompatible


" Plugins
call plug#begin()
""Theme
" Plug 'acoustichero/goldenrod.vim' 
Plug 'preservim/nerdcommenter'
Plug 'tpope/vim-sensible'
Plug 'suan/vim-instant-markdown', { 'for' : 'markdown' }
Plug 'xuhdev/vim-latex-live-preview', { 'for' : 'tex' }
Plug 'itchyny/lightline.vim'
Plug 'SirVer/ultisnips'
Plug 'ervandew/supertab'
Plug 'honza/vim-snippets'
Plug 'yggdroot/indentline'
Plug 'ap/vim-css-color'
" Highlighting search patterns when needed
Plug 'romainl/vim-cool' 
Plug 'sainnhe/sonokai'
Plug 'sheerun/vim-polyglot'
" Plug 'ycm-core/YouCompleteMe'
Plug 'lervag/vimtex'
Plug 'scrooloose/nerdtree' 
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tacahiroy/ctrlp-funky'
" Plug 'nikvdp/ejs-syntax'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'
Plug 'szw/vim-maximizer'
" Plug 'ymagossou/Conque-GDB', { 'for': 'c' }
Plug 'puremourning/vimspector'
Plug 'jason0x43/vim-wildgitignore'
call plug#end()

" Command
command Src execute "so " . $MYVIMRC

" Disabeling q: and Q (q: for search through last vim commands, Q for Ex mode)
nnoremap q: <nop>
nnoremap Q <nop>

" Look and feel
"" Colorscheme
set background=dark 

" let g:sonokai_style = 'andromeda'
colorscheme sonokai

""" Lightline colorscheme
let g:lightline = { 'colorscheme' : 'sonokai' }

""" Changing cursor style (insert: |, normal: _, both blinking)
let &t_SI = "\<Esc>[5 q"
let &t_SR = "\<Esc>[1 q"
let &t_EI = "\<Esc>[3 q"

"" Enable transparency
hi Normal ctermbg=None 
hi Terminal ctermbg=None 


"" Spelling errors
hi SpellBad ctermfg=red

"" Show keystrokes as they are pressed
set showcmd
set hlsearch incsearch
set wildmenu wildmode=longest:full,full
""" Ignore binary files
set wildignore+=*.a,*.o,*.class
""" Ignore image files
set wildignore+=*.png,*.jpg,*.bmp,*.gif,*.ico
""" Ignore useless directories
set wildignore+=.DS_Store,.git,.hg,.svn
""" Ignore temporary files directories
set wildignore+=+*~,*.sw?,*.tmp
set updatetime=100
set timeoutlen=1000 ttimeoutlen=10


" 
set number relativenumber
set tabstop=4 shiftwidth=4 expandtab
set tw=80
set scrolloff=8

"" Left side number column foreground color
hi LineNr ctermfg=darkgray

"" What to show when ':set list' is called (to show tabs, end of lines, spaces, etc.)
" set listchars=eol:¬,tab:\ »\ ,space:·,trail:█

"" Splits
set splitright

"" Smart case for searching
set ignorecase smartcase

" Mapings
let mapleader = ","

"" Saving and quitting
map <leader>s :w<Cr>
map <leader>jk :wq<Cr>
map <leader>q :q<Cr>
map <leader>Q :q!<Cr>

"" Fixing Y
map Y y$

"" Keeping it centered
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap J mzJ`z

"" Undo breakpoints
inoremap , ,<c-g>u
inoremap . .<c-g>u
inoremap ! !<c-g>u
inoremap ? ?<c-g>u
inoremap ( (<c-g>u
inoremap ) )<c-g>u
inoremap [ [<c-g>u
inoremap ] ]<c-g>u
inoremap { {<c-g>u
inoremap } }<c-g>u

"" Split window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

""" Same but for the terminal
tmap <C-h> <C-w>h
tmap <C-j> <C-w>j
tmap <C-k> <C-w>k
tmap <C-l> <C-w>l

"" Renaming vairables
map <leader>r :s/<C-R><C-W>//g<left><left>
map <leader>R :%s/<C-R><C-W>//gc<left><left><left>

"" Rapiddly correcting mispelled word
map <leader>z 1z=

"" Print and paste from clipboard
map <leader>p "+p
map <leader>P "+P
map <leader>y "+y
map <leader>Y "+Y
map <leader>d "+d
map <leader>D "+D

vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv


"" Fixing mistakes I usually make
imap <C-b> <Esc>b

"" Terminal mappings
tmap <C-n> <C-w>N

" Filetype specific settings
"" Setting the filetype of service files
" augroup Compliers
"     autocmd!
"     autocmd Filetype c,cpp command -nargs=* Make make <args> | cwindow 10 
"     autocmd Filetype c,cpp nmap <silent> <leader>m :make compile \| cwindow 10 <cr>
" augroup END

augroup RememberLastPosition
    autocmd!
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"zv" | endif
augroup END

augroup Term
    autocmd!
    autocmd TerminalOpen * set nonumber | set norelativenumber
augroup END

"" Setting the filetype of service files
augroup Services
    autocmd!
    autocmd BufNewFile,BufRead *.service set ft=dosini
augroup END

"" Reloading configs after saving files
augroup SetSpell
    autocmd!
    autocmd FileType tex,markdown set spell
augroup END

"" Reloading configs after saving files
augroup ReloadConfigs
    autocmd!
    autocmd BufWritePost dunstrc silent exec "!killall dunst" | redraw!
augroup END

"" Disable the indent lines plugins on files that use italize / bold / etc...
"" because it gets wierd
augroup DisableIndents
    autocmd!
    autocmd FileType tex,markdown IndentLinesDisable
augroup END



" Plugin settings
"" Nerd commenter
let g:NERDSpaceDelims = 1
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitspace = 1
let g:NERDToggleCheckAllLines = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCustomDelimiters = { 'jas': { 'left': '//','right': '' }, 'python': {'left': '#', 'right': '' } }

"" Markdown previewer
let g:instant_markdown_browser = "qutebrowser --target window"

"" LateX previewer
let g:livepreview_previewer = 'zathura'

"" Lightline
""" Enable statuline for single buffer
set laststatus=2
""" Disable '--INSERT--' below the status line
set noshowmode

"" Ultisnips
""" Trigger configuration
" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
" let g:UltiSnipsExpandTrigger="<c-j>"
" let g:UltiSnipsJumpForwardTrigger="<c-j>"
" let g:UltiSnipsJumpBackwardTrigger="<c-k>"

""" Split snippet edit vertically
let g:UltiSnipsEditSplit="vertical"

""" Help ultisnips find the location of the dot directory of vim
let g:UltiSnipsSnippetsDir = expand("$XDG_CONFIG_HOME/vim/ultisnips")
" let g:UltiSnipsSnippetDirectories = [expand("$XDG_CONFIG_HOME/vim/ultisnips"), 'UltiSnips']
" let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit = "~/.config/vim/plugged/vim-snippets/snippets"

augroup LATEX_RTP
    autocmd!
    autocmd Filetype tex set rtp-=~/.dotfiles/vim/.config/vim/plugged/vim-snippets " to fix the issue with vim-polyglot and snippets duplication of snippets
augroup END

let g:CoolTotalMatches = 1

"" Indentline
let g:indentLine_char = '│'
let g:indentLine_color_term = 237

"" YouCompleteMe
""" Disable on latex files
let g:ycm_filetype_blacklist = {'tex' : 1,
            \ 'markdown': 1
            \ }
""" Make tab of YCM and Ultisnips work nicely
" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

"" NERDTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
augroup NERDTree
    """ Start NERDTree.
    autocmd StdinReadPre * let s:std_in=1
    " If a file is specified, move the cursor to its window.
    " autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
    " If no file was specified, or if it is a directory
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    """ Exit Vim if NERDTree is the only window left.
    autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
augroup END

"" vimtex
let g:vimtex_quickfix_ignore_filters = [
            \ '\v(Over|Under)full',
            \]

augroup MyVimtex
  autocmd!
  " autocmd User VimtexEventQuit call vimtex#latexmk#clean(0)
  autocmd User VimtexEventQuit VimtexClean
augroup END
" let g:vimtex_enabled = 0
let g:tex_fast = 'bMpr'
" let g:tex_fast = ''


"" CtrlP
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_root_markers = ['pom.xml']

" if executable('ag')
"   " Use Ag over Grep
"   set grepprg=ag\ --nogroup\ --nocolor
" 
"   " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
"   let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
" endif
let g:ctrlp_funky_syntax_highlight = 1

nnoremap <Leader>fu :CtrlPFunky<Cr>

"" Auto-pairs
let g:AutoPairsShortcutToggle = '<leader>('

augroup Latex_Dollar_Separator
    autocmd!
    autocmd FileType tex let g:AutoPairs = {
                \ '(':')',
                \ '[':']',
                \ '{':'}',
                \ "$":"$",
                \ "$$":"$$",
                \ }
augroup END

"" ConqueGDB
let g:ConqueTerm_Color = 2         " 1: strip color after 200 lines, 2: always with color
let g:ConqueTerm_CloseOnEnd = 1    " close conque when program ends running
let g:ConqueTerm_StartMessages = 0 " display warning messages if conqueTerm is configured incorrectly 
let g:ConqueGdb_Leader = '\' 

"" Maximizer
nnoremap <leader>m :MaximizerToggle!<CR>
vnoremap <leader>m :MaximizerToggle!<CR>gv

"" Vimspector
nmap <leader>dd <Plug>VimspectorContinue
nmap <leader>dl <Plug>VimspectorStepInto
nmap <leader>dj <Plug>VimspectorStepOver
nmap <leader>dk <Plug>VimspectorStepOut
nmap <leader>d_ <Plug>VimspectorRestart
nmap <leader>de :call vimspector#Reset()<Cr>


nmap <leader>drc <Plug>VimspectorRunToCursor
nmap <leader>dbp <Plug>VimspectorToggleBreakpoint
nmap <leader>dcbp <Plug>VimspectorToggleConditionalBreakpoint
